# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificuser',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='is_member',
            field=models.BooleanField(default=True),
        ),
    ]
