# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170717_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scientificuser',
            options={},
        ),
    ]
