# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170717_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificuser',
            name='cv',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='scientificuser',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
