# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170720_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificuser',
            name='grad',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='scientificuser',
            name='speciality',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
