# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170718_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='HOME', max_length=120),
        ),
    ]
