# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timing',
            field=models.DateField(default=datetime.datetime(2017, 7, 19, 11, 15, 10, 563053, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
