# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170719_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(default='\u062c\u0627\u0645\u0639\u0629 \u0648\u0647\u0631\u0627\u06461 \u0623\u062d\u0645\u062f \u0628\u0646 \u0628\u0644\u0629', max_length=120),
        ),
    ]
