# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='categorie',
        ),
    ]
