# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 12:22
from __future__ import unicode_literals

import articles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='post',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=articles.models.upload_location),
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.Categorie'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
