# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20170731_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('FRENCH', 'Fr'), ('ARABE', 'Ar'), ('ENGLISH', 'En')], default='ARABE', max_length=60),
        ),
    ]
